### ISSUE TITLE
part 3 feedback

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/TrangQuach-Project#2]
My various comments, listed in no particular order:

Please remove any folders/files and text inside files that is not part of your project.

For your table question: I usually make a data frame and then use kable/xtable or a similar package for formatting. That usually makes ok enough tables. Most journals reformat it anyway. I’m not sure if you can get a tableone output into a word file. I know Brian has a lot of experience doing tables in R Markdown and I think he’s worked with the tableone package. You could ask him (or Yang).

Your main document contains very little content. I can therefore not provide further feedback on the overall project.

Make sure you use/include citations as specified in the instructions (with a reference manager/bibtex file).

If you want more feedback on specific aspects, let me know either by replying to this Issue or email.

**Comment by TrangQuach** [comment]
Dear Dr. Handel,

Thank you so much for your responses. To create table one, I tried tableone, finalfit, and Table1 packages. The tableone package does not give me the good format. Maybe, the table from tableone packages can be modified to better and I do not know. I will ask Brian. 

In this period, I am busy with other classes. So, you do not see I wrote the manuscript. I will try to do better next time.

Thanks.
